-- ================================================================
-- SQL DDL TEMPLATE (TOPIC 04)
-- ================================================================
-- WHAT SHOULD BE ADDED HERE:
-- 1) Full PostgreSQL DDL for your finalized schema.
-- 2) CREATE TABLE statements for all entities from your ER diagram.
-- 3) Primary keys, foreign keys, NOT NULL, UNIQUE, CHECK constraints.
-- 4) Indexes for important search/join columns.
-- 5) Clean structure and comments (group by tables/constraints/indexes).
--
-- RECOMMENDED ORDER:
-- 1) Tables
-- 2) Constraints (if not inline)
-- 3) Indexes
--
-- TEAM NOTE:
-- Add short attribution comments for who implemented which part.
-- Example:
-- [Name] - users, roles, permissions tables
-- [Name] - orders, payments, invoices tables
--
-- IMPORTANT:
-- The script must run in PostgreSQL and produce a working schema that
-- matches your approved ER diagram and conceptual schema.
-- Submit this as one SQL file.
-- ================================================================

-- Add your DDL below this line

-- =========================================================
-- Fitness Center Management System
-- PostgreSQL DDL Schema
-- =========================================================

CREATE SCHEMA IF NOT EXISTS gym;

-- =========================================================
-- ENUM TYPES
--
-- All enum values are lowercase with underscores.
-- Adding new values requires ALTER TYPE ... ADD VALUE,
-- which cannot be run inside a transaction block in PostgreSQL.
-- Removing or renaming values requires recreating the type
-- and all columns that depend on it.
-- =========================================================

-- Membership plan category.
-- New plan types require ALTER TYPE, not a new row in memberships.
CREATE TYPE gym.membership_type AS ENUM (
    'monthly',
    'yearly',
    'premium'
);

-- Lifecycle of a single attendance record.
-- booked    → member reserved a spot, has not arrived yet
-- attended  → member physically checked in
-- no_show   → session passed without check-in
-- cancelled → member cancelled their booking before the session
CREATE TYPE gym.attendance_status AS ENUM (
    'booked',
    'attended',
    'no_show',
    'cancelled'
);

-- Determines which day-detail table is used:
-- daily   → no day table needed
-- weekly  → days stored in rule_week_days
-- monthly → days stored in rule_month_days
CREATE TYPE gym.recurrence_frequency AS ENUM (
    'daily',
    'weekly',
    'monthly'
);

-- ISO weekday abbreviations, lowercase.
-- Used in rule_week_days and trainer_work_schedule.
CREATE TYPE gym.day_of_week AS ENUM (
    'mon',
    'tue',
    'wed',
    'thu',
    'fri',
    'sat',
    'sun'
);

-- Lifecycle of a materialized class session.
-- scheduled → generated by background job, open for booking
-- cancelled → session will not take place
-- completed → session has ended
CREATE TYPE gym.class_schedule_status AS ENUM (
    'scheduled',
    'cancelled',
    'completed'
);

-- Lifecycle of a personal training session.
-- Mirrors class_schedule_status but kept separate
-- to allow independent evolution of the two flows.
CREATE TYPE gym.personal_training_status AS ENUM (
    'scheduled',
    'completed',
    'cancelled'
);

-- Approval workflow for trainer leave requests.
-- pending  → submitted, awaiting manager decision
-- approved → leave confirmed, trainer unavailable in that period
-- rejected → leave denied, trainer remains scheduled
CREATE TYPE gym.leave_status AS ENUM (
    'pending',
    'approved',
    'rejected'
);

-- Category of a trainer leave request.
CREATE TYPE gym.leave_type AS ENUM (
    'sick',
    'vacation',
    'personal'
);

-- Operational state of a piece of equipment.
-- available   → ready for use
-- under_repair → temporarily out of service
-- broken      → out of service indefinitely until repaired
CREATE TYPE gym.equipment_status AS ENUM (
    'available',
    'under_repair',
    'broken'
);

-- Lifecycle of a member fitness goal.
-- in_progress → actively being tracked
-- completed   → target reached
-- abandoned   → member stopped tracking
CREATE TYPE gym.goal_status AS ENUM (
    'in_progress',
    'completed',
    'abandoned'
);

-- =========================================================
-- PERSON AND TRAINER SPECIALIZATIONS
-- RESPONSIBLE BOHDAN BOHELSKYI
-- =========================================================

-- Base identity record shared by members and trainers.
-- Business tables never reference person_id directly —
-- they always go through members.member_id or trainers.trainer_id.
CREATE TABLE gym.persons (
    person_id  BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name  VARCHAR(255) NOT NULL,

    -- Optional but validated when provided.
    -- 254 chars is the RFC 5321 maximum for email addresses.
    email      VARCHAR(254) UNIQUE,

    -- Required as a fallback contact when email is absent.
    -- Stored as text to preserve leading + and avoid integer overflow.
    phone      VARCHAR(20) UNIQUE NOT NULL,

    birth_date DATE,

    -- Allows optional leading +, then digits only.
    -- Does not validate country codes or length — intentionally permissive.
    CONSTRAINT ck_person_phone_format
        CHECK (phone ~ '^\+?[0-9]+$'),

    -- Basic structural validation. Does not guarantee deliverability.
    CONSTRAINT ck_person_email_format
        CHECK (email ~ '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'),

    -- Sanity bounds: no births before records began, and not in the future.
    CONSTRAINT ck_person_birth_date
        CHECK (birth_date >= '1900-01-01' AND birth_date < CURRENT_DATE)
);

-- A person employed as a trainer.
-- UNIQUE on person_id enforces the 1-to-1 relationship with persons.
CREATE TABLE gym.trainers (
    trainer_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    person_id  BIGINT UNIQUE NOT NULL,

    -- Defaults to today so the column is never accidentally NULL on insert.
    hire_date  DATE NOT NULL DEFAULT CURRENT_DATE,

    -- Hire date cannot be in the future — guards against data entry errors.
    CONSTRAINT ck_trainer_hire_date
        CHECK (hire_date <= CURRENT_DATE),

    CONSTRAINT fk_trainer_person
        FOREIGN KEY (person_id) REFERENCES gym.persons(person_id)
);

-- Catalogue of trainer qualification types (e.g. 'Yoga', 'HIIT').
-- Rows are never deleted in normal operation — use deactivation at the
-- application level if a specialization becomes obsolete.
CREATE TABLE gym.specializations (
    specialization_id   BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    -- UNIQUE prevents duplicate qualification names.
    specialization_name VARCHAR(255) NOT NULL UNIQUE
);

-- Many-to-many junction: which specializations a trainer holds.
-- ON DELETE CASCADE  — removing a trainer also removes their qualifications.
-- ON DELETE RESTRICT — prevents deleting a specialization that is still assigned.
CREATE TABLE gym.trainer_specializations (
    trainer_id        BIGINT NOT NULL,
    specialization_id BIGINT NOT NULL,

    -- Composite PK prevents the same specialization being assigned twice.
    CONSTRAINT pk_trainers_specs
        PRIMARY KEY (trainer_id, specialization_id),

    CONSTRAINT fk_trainers_specs_trainers
        FOREIGN KEY (trainer_id) REFERENCES gym.trainers(trainer_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_trainers_specs_spec
        FOREIGN KEY (specialization_id) REFERENCES gym.specializations(specialization_id)
        ON DELETE RESTRICT
);

-- =========================================================
-- CLASS AND SCHEDULING MANAGEMENT
-- RESPONSIBLE OLEKSANDR CHURA
-- =========================================================

-- Physical spaces where classes and personal training take place.
CREATE TABLE gym.rooms (
    room_id  BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name     VARCHAR(100) NOT NULL,

    -- Minimum of 2 enforced: a class with 1 seat makes no operational sense.
    -- NULL is allowed for rooms without a defined capacity limit.
    capacity INTEGER CHECK (capacity > 1)
);

-- Catalogue of class types offered by the gym.
-- No scheduling data lives here — only the definition of what the class is.
CREATE TABLE gym.class_templates (
    class_id         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    -- UNIQUE prevents two distinct class types from sharing a name.
    class_name       VARCHAR(150) NOT NULL UNIQUE,
    description      VARCHAR(500),

    -- Must be positive — a zero-minute class cannot be scheduled.
    duration_minutes INTEGER CHECK (duration_minutes > 0),

    -- Overrides room capacity when set. NULL means defer to room.capacity.
    -- Minimum of 2 for the same reason as rooms.capacity.
    capacity         INTEGER CHECK (capacity > 1)
);

-- Defines a repeating assignment: a trainer runs a class in a room
-- on a recurring pattern. Acts as the master rule from which
-- individual class_schedule rows are generated.
--
-- Day detail is stored separately:
--   frequency = 'weekly'  → rows in rule_week_days
--   frequency = 'monthly' → rows in rule_month_days
--   frequency = 'daily'   → no day table needed
CREATE TABLE gym.class_recurrence_rules (
    rule_id    BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    class_id   BIGINT NOT NULL,
    trainer_id BIGINT NOT NULL,
    room_id    BIGINT NOT NULL,
    frequency  gym.recurrence_frequency NOT NULL,
    start_time TIME NOT NULL,
    start_date DATE NOT NULL,
    end_date   DATE NOT NULL,

    -- A rule that ends before it starts would generate zero sessions.
    CONSTRAINT chk_recurrence_rules_date_range
        CHECK (end_date >= start_date),

    CONSTRAINT fk_recurrence_rules_class
        FOREIGN KEY (class_id) REFERENCES gym.class_templates(class_id),
    CONSTRAINT fk_recurrence_rules_trainer
        FOREIGN KEY (trainer_id) REFERENCES gym.trainers(trainer_id),
    CONSTRAINT fk_recurrence_rules_room
        FOREIGN KEY (room_id) REFERENCES gym.rooms(room_id)
);

-- Days of the week for weekly recurrence rules.
-- One row per day per rule: a Mon+Wed class has two rows for the same rule_id.
-- Only populated when parent rule has frequency = 'weekly'.
-- ON DELETE CASCADE — removing the rule automatically removes its day rows.
CREATE TABLE gym.rule_week_days (
    rule_id     BIGINT NOT NULL,
    day_of_week gym.day_of_week NOT NULL,

    -- Composite PK prevents the same day being added twice to one rule.
    PRIMARY KEY (rule_id, day_of_week),

    CONSTRAINT fk_rule_week_days_rule
        FOREIGN KEY (rule_id) REFERENCES gym.class_recurrence_rules(rule_id)
        ON DELETE CASCADE
);

-- Days of the month for monthly recurrence rules.
-- One row per day per rule: a rule on the 1st and 15th has two rows.
-- Only populated when parent rule has frequency = 'monthly'.
-- ON DELETE CASCADE — removing the rule automatically removes its day rows.
--
-- Limitation: day 29, 30, 31 may not exist in every month.
-- The application layer must skip non-existent dates when materializing sessions
-- (e.g. Feb 30 is silently skipped, not an error).
CREATE TABLE gym.rule_month_days (
    rule_id      BIGINT NOT NULL,
    day_of_month INTEGER NOT NULL,

    -- Constrains to valid calendar day range.
    CONSTRAINT chk_rule_month_days_range
        CHECK (day_of_month BETWEEN 1 AND 31),

    -- Composite PK prevents the same day being added twice to one rule.
    PRIMARY KEY (rule_id, day_of_month),

    CONSTRAINT fk_rule_month_days_rule
        FOREIGN KEY (rule_id) REFERENCES gym.class_recurrence_rules(rule_id)
        ON DELETE CASCADE
);

-- Individual materialized class sessions on the calendar.
-- Generated from class_recurrence_rules by a background job.
--
-- class_id, trainer_id, and room_id are denormalized from the rule
-- to support per-session overrides (substitute trainer, room swap)
-- without modifying the master rule. When a session matches its rule
-- exactly, these columns will be identical to the rule's values.
-- When they differ, the application should record the reason separately
-- (e.g. an override_reason column added in a future migration).
CREATE TABLE gym.class_schedule (
    class_schedule_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    rule_id           BIGINT NOT NULL,
    class_id          BIGINT NOT NULL,
    trainer_id        BIGINT NOT NULL,
    room_id           BIGINT NOT NULL,

    -- TIMESTAMPTZ stores timezone-aware timestamps.
    -- All datetimes are stored in UTC; conversion to local time
    -- is handled at the application layer.
    start_datetime    TIMESTAMPTZ NOT NULL,
    end_datetime      TIMESTAMPTZ NOT NULL,
    status            gym.class_schedule_status NOT NULL,

    -- Strict inequality: a session must have positive duration.
    CONSTRAINT chk_class_schedule_datetime_range
        CHECK (end_datetime > start_datetime),

    CONSTRAINT fk_class_schedule_rule
        FOREIGN KEY (rule_id) REFERENCES gym.class_recurrence_rules(rule_id),
    CONSTRAINT fk_class_schedule_class
        FOREIGN KEY (class_id) REFERENCES gym.class_templates(class_id),
    CONSTRAINT fk_class_schedule_trainer
        FOREIGN KEY (trainer_id) REFERENCES gym.trainers(trainer_id),
    CONSTRAINT fk_class_schedule_room
        FOREIGN KEY (room_id) REFERENCES gym.rooms(room_id)
);

-- =========================================================
-- MEMBERSHIP MANAGEMENT
-- RESPONSIBLE OLEH SVYRYDENKO
-- =========================================================

-- Versioned membership products.
-- Prices are never edited in place — when a price changes, a new row
-- is inserted with a new valid_from and the old row gets a valid_to date.
-- This preserves full price history and ensures members_memberships rows
-- always point to the exact price that was active at signup.
--
-- Query for currently active products: WHERE valid_to IS NULL
CREATE TABLE gym.memberships (
    membership_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    type          gym.membership_type NOT NULL,

    -- DECIMAL(10,2) supports values up to 99,999,999.99.
    -- Negative prices are nonsensical and blocked by the check.
    price         DECIMAL(10,2) NOT NULL CHECK (price > 0),

    -- ISO 4217 three-letter currency code (e.g. 'UAH', 'EUR', 'USD').
    -- CHAR(3) enforces the exact length at the DB level.
    currency      CHAR(3) NOT NULL DEFAULT 'UAH',

    valid_from    DATE NOT NULL,

    -- NULL means this product version is currently active.
    valid_to      DATE,

    -- Prevents a product version from ending before it starts.
    CONSTRAINT chk_memberships_date_range
        CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

-- A person registered as a gym member.
-- UNIQUE on person_id enforces the 1-to-1 relationship with persons.
-- Membership history is tracked in members_memberships, not here.
CREATE TABLE gym.members (
    member_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    person_id BIGINT UNIQUE NOT NULL,

    CONSTRAINT fk_members_person
        FOREIGN KEY (person_id) REFERENCES gym.persons(person_id)
);

-- Records which membership product a member enrolled in and when.
-- Supports full history: a member can have multiple rows over time
-- (renewals, upgrades, lapses). The membership_id FK points to the
-- exact versioned product row, implicitly snapshotting the price.
CREATE TABLE gym.members_memberships (
    members_membership_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    membership_id         BIGINT NOT NULL,
    member_id             BIGINT NOT NULL,
    start_date            DATE NOT NULL,

    -- NULL means the enrollment is open-ended (no defined expiry).
    end_date              DATE,

    -- Percentage discount applied at signup. 0 = no discount, 100 = free.
    -- Stored as an integer; fractional discounts are not supported.
    discount              INTEGER DEFAULT 0 CHECK (discount BETWEEN 0 AND 100),

    CONSTRAINT fk_mm_membership
        FOREIGN KEY (membership_id) REFERENCES gym.memberships(membership_id),
    CONSTRAINT fk_mm_member
        FOREIGN KEY (member_id) REFERENCES gym.members(member_id),

    -- Prevents an enrollment from ending before it begins.
    CONSTRAINT chk_mm_date_range
        CHECK (end_date IS NULL OR end_date >= start_date)
);

-- Records a member's booking or physical presence at a class session.
-- One row per member per session.
--
-- check_in_time is NULL until the member physically arrives.
-- It remains NULL for no_show and cancelled records.
CREATE TABLE gym.attendance (
    attendance_id     BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    member_id         BIGINT NOT NULL,
    class_schedule_id BIGINT NOT NULL,

    -- Nullable: populated on physical arrival, NULL for no_show / cancelled.
    check_in_time     TIMESTAMPTZ,

    status            gym.attendance_status NOT NULL,

    CONSTRAINT fk_attendance_member
        FOREIGN KEY (member_id) REFERENCES gym.members(member_id),
    CONSTRAINT fk_attendance_schedule
        FOREIGN KEY (class_schedule_id) REFERENCES gym.class_schedule(class_schedule_id)
);

-- =========================================================
-- EQUIPMENT AND GOAL TRACKING
-- RESPONSIBLE DMYTRO TOKARIYEV
-- =========================================================

-- Gym equipment inventory. Not linked to scheduling —
-- used for maintenance tracking and operational status only.
CREATE TABLE gym.equipment (
    equipment_id     BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name             VARCHAR(150) NOT NULL,

    -- Defaults to 'available' on insert.
    -- Use UPDATE to transition: available → under_repair → available / broken.
    status           gym.equipment_status NOT NULL DEFAULT 'available',

    -- NULL means maintenance has never been recorded.
    -- Cannot be a future date — maintenance must have already happened.
    last_maintenance DATE,

    CONSTRAINT ck_equipment_maintenance_not_future
        CHECK (last_maintenance IS NULL OR last_maintenance <= CURRENT_DATE)
);

-- A fitness goal set by a member.
-- target_value and current_state in progress are both VARCHAR to support
-- any goal type: numeric (e.g. '80 kg'), qualitative ('run 5k'), or habit-based.
CREATE TABLE gym.goals (
    goal_id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    member_id        BIGINT NOT NULL,
    goal_description VARCHAR(255) NOT NULL,

    -- Optional free-text target. Examples: '75', '5km', '20 pull-ups'.
    target_value     VARCHAR(100),

    -- Optional target date for the goal.
    -- Lower bound of 2000-01-01 is a sanity check against data entry errors.
    deadline         DATE,

    -- Defaults to 'in_progress' on creation.
    status           gym.goal_status NOT NULL DEFAULT 'in_progress',

    created_at       DATE NOT NULL DEFAULT CURRENT_DATE,

    CONSTRAINT ck_goals_deadline
        CHECK (deadline IS NULL OR deadline >= '2000-01-01')
);

-- A timestamped check-in entry against a goal.
-- Multiple entries per goal build a progress timeline.
--
-- ON DELETE CASCADE — deleting a goal also deletes all its progress records.
-- UNIQUE (goal_id, check_date) — only one progress entry per goal per day.
--   To update today's entry, UPDATE the existing row rather than inserting a new one.
CREATE TABLE gym.progress (
    progress_id   BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    goal_id       BIGINT NOT NULL,

    -- Free-text snapshot of current state. Examples: '78.5', 'completed week 3'.
    current_state VARCHAR(255) NOT NULL,
    notes         VARCHAR(500),
    check_date    DATE NOT NULL DEFAULT CURRENT_DATE,

    CONSTRAINT fk_progress_goal
        FOREIGN KEY (goal_id) REFERENCES gym.goals(goal_id)
        ON DELETE CASCADE,

    -- One entry per goal per day. Inserting a second entry for the same day
    -- will raise a unique violation — use UPDATE instead.
    CONSTRAINT uq_progress_goal_date
        UNIQUE (goal_id, check_date)
);

-- =========================================================
-- PERSONAL TRAINING MANAGEMENT
-- RESPONSIBLE ANDREW CHERNUHA
-- =========================================================

-- One-on-one sessions booked between a member and a trainer,
-- outside the group class scheduling system.
--
-- uq_member_time  — a member cannot have two personal sessions at the same time.
-- uq_trainer_time — a trainer cannot run two personal sessions at the same time.
-- Note: these constraints do not cross-check against class_schedule.
--       Conflict detection between personal training and group classes
--       must be handled at the application layer.
CREATE TABLE gym.personal_training (
    session_id    BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    member_id     BIGINT NOT NULL,
    trainer_id    BIGINT NOT NULL,
    training_date TIMESTAMPTZ NOT NULL,
    status        gym.personal_training_status NOT NULL DEFAULT 'scheduled',

    CONSTRAINT fk_personal_training_member
        FOREIGN KEY (member_id) REFERENCES gym.members(member_id),
    CONSTRAINT fk_personal_training_trainer
        FOREIGN KEY (trainer_id) REFERENCES gym.trainers(trainer_id),

    -- Prevents double-booking a member at the same timestamp.
    CONSTRAINT uq_member_time
        UNIQUE (member_id, training_date),

    -- Prevents double-booking a trainer at the same timestamp.
    CONSTRAINT uq_trainer_time
        UNIQUE (trainer_id, training_date)
);

-- Regular weekly working hours for a trainer.
-- Used by the application to validate that scheduled sessions
-- fall within a trainer's available hours.
--
-- uq_trainer_day — one schedule row per trainer per weekday.
--   To change hours for a day, UPDATE the existing row; do not insert a duplicate.
-- is_active = FALSE allows suspending a day without deleting the row,
--   preserving history and making reactivation a simple UPDATE.
CREATE TABLE gym.trainer_work_schedule (
    work_schedule_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    trainer_id       BIGINT NOT NULL,
    day_of_week      gym.day_of_week NOT NULL,
    start_time       TIME NOT NULL,
    end_time         TIME NOT NULL,

    -- Prevents a shift from ending before or at its start time.
    CONSTRAINT chk_work_schedule_time_range
        CHECK (end_time > start_time),

    is_active        BOOLEAN DEFAULT TRUE,

    CONSTRAINT fk_work_schedule_trainer
        FOREIGN KEY (trainer_id) REFERENCES gym.trainers(trainer_id),

    -- One active schedule row per trainer per weekday.
    CONSTRAINT uq_trainer_day
        UNIQUE (trainer_id, day_of_week)
);

-- Leave requests for trainers (sick days, vacation, personal).
-- The application should cross-reference approved leave records
-- when generating class_schedule rows to flag conflicts.
--
-- Limitation: chk_leaves_date_range allows end_date = NULL (open-ended leave),
-- but the CHECK only fires when end_date IS NOT NULL.
-- Open-ended leaves must be closed explicitly via UPDATE.
CREATE TABLE gym.trainer_leaves (
    leave_id   BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    trainer_id BIGINT NOT NULL,
    leave_type gym.leave_type NOT NULL,
    start_date DATE NOT NULL,

    -- NULL means the leave has no defined end date (e.g. extended sick leave).
    end_date   DATE,

    status     gym.leave_status NOT NULL,
    notes      VARCHAR(500),

    CONSTRAINT fk_leaves_trainer
        FOREIGN KEY (trainer_id) REFERENCES gym.trainers(trainer_id),

    -- Prevents end date from preceding start date when end_date is provided.
    CONSTRAINT chk_leaves_date_range
        CHECK (end_date >= start_date)
);

-- =========================================================
-- INDEXES
--
-- All indexes cover foreign key columns.
-- PostgreSQL does not automatically index FK columns —
-- without these, FK lookups and JOIN operations on large tables
-- would fall back to sequential scans.
--
-- Additional functional index on class_schedule.start_datetime
-- supports calendar queries and range scans (e.g. "all sessions this week").
-- =========================================================

-- gym.trainers
-- Supports lookup of a trainer by their person record.
CREATE INDEX idx_trainers_person_id
    ON gym.trainers(person_id);

-- gym.members
-- Supports lookup of a member by their person record.
CREATE INDEX idx_members_person_id
    ON gym.members(person_id);

-- gym.trainer_specializations
-- Supports "which trainers hold specialization X" and
-- "which specializations does trainer Y hold" queries.
CREATE INDEX idx_trainer_specializations_trainer_id
    ON gym.trainer_specializations(trainer_id);

CREATE INDEX idx_trainer_specializations_specialization_id
    ON gym.trainer_specializations(specialization_id);

-- gym.class_recurrence_rules
-- Supports filtering rules by class type, trainer, or room.
CREATE INDEX idx_class_recurrence_rules_class_id
    ON gym.class_recurrence_rules(class_id);

CREATE INDEX idx_class_recurrence_rules_trainer_id
    ON gym.class_recurrence_rules(trainer_id);

CREATE INDEX idx_class_recurrence_rules_room_id
    ON gym.class_recurrence_rules(room_id);

-- gym.class_schedule
-- FK indexes for trainer and room lookups.
CREATE INDEX idx_class_schedule_rule_id
    ON gym.class_schedule(rule_id);

CREATE INDEX idx_class_schedule_trainer_id
    ON gym.class_schedule(trainer_id);

CREATE INDEX idx_class_schedule_room_id
    ON gym.class_schedule(room_id);

-- Functional index: supports date-range calendar queries
-- such as "all sessions today" or "sessions in the next 7 days".
CREATE INDEX idx_class_schedule_start_datetime
    ON gym.class_schedule(start_datetime);

-- gym.members_memberships
-- Supports "all memberships for member X" and
-- "all members on plan Y" queries.
CREATE INDEX idx_members_memberships_member_id
    ON gym.members_memberships(member_id);

CREATE INDEX idx_members_memberships_membership_id
    ON gym.members_memberships(membership_id);

-- gym.attendance
-- Supports "all attendance records for member X" and
-- "all bookings for session Y" queries.
CREATE INDEX idx_attendance_member_id
    ON gym.attendance(member_id);

-- Ensures only one active membership per member.
CREATE UNIQUE INDEX uq_members_active_membership
    ON gym.members_memberships(member_id)
    WHERE end_date IS NULL;

CREATE INDEX idx_attendance_class_schedule_id
    ON gym.attendance(class_schedule_id);

-- gym.goals
-- Supports "all goals for member X" queries.
CREATE INDEX idx_goals_member_id
    ON gym.goals(member_id);

-- gym.progress
-- Supports "all progress entries for goal X" queries.
CREATE INDEX idx_progress_goal_id
    ON gym.progress(goal_id);

-- gym.personal_training
-- Supports "all sessions for member X" and
-- "all sessions for trainer Y" queries.
CREATE INDEX idx_personal_training_member_id
    ON gym.personal_training(member_id);

CREATE INDEX idx_personal_training_trainer_id
    ON gym.personal_training(trainer_id);

-- gym.trainer_work_schedule
-- Supports "what days does trainer X work" queries.
CREATE INDEX idx_trainer_work_schedule_trainer_id
    ON gym.trainer_work_schedule(trainer_id);

-- gym.trainer_leaves
-- Supports "all leave requests for trainer X" queries.
CREATE INDEX idx_trainer_leaves_trainer_id
    ON gym.trainer_leaves(trainer_id);

-- =========================================================
-- COMMENTS
-- =========================================================

COMMENT ON SCHEMA gym IS 'Gym management system schema';

-- persons
COMMENT ON TABLE  gym.persons IS 'Base identity record for every person in the system. Members and trainers extend this via a 1-to-1 FK. Business tables never reference person_id directly.';
COMMENT ON COLUMN gym.persons.email IS 'Optional. RFC 5321 max length of 254 chars. Validated by ck_person_email_format.';
COMMENT ON COLUMN gym.persons.phone IS 'Required. Stored as text to preserve leading + sign. Validated by ck_person_phone_format.';
COMMENT ON COLUMN gym.persons.birth_date IS 'Optional. Must be between 1900-01-01 and yesterday. Validated by ck_person_birth_date.';

-- trainers
COMMENT ON TABLE  gym.trainers IS 'A person employed as a trainer. Extends persons via a 1-to-1 relationship.';
COMMENT ON COLUMN gym.trainers.hire_date IS 'Cannot be in the future. Defaults to CURRENT_DATE on insert.';

-- specializations
COMMENT ON TABLE gym.specializations IS 'Catalogue of trainer qualification types. Rows should not be deleted once assigned — deactivate at application level instead.';

-- trainer_specializations
COMMENT ON TABLE gym.trainer_specializations IS 'Many-to-many: which specializations a trainer holds. Composite PK prevents duplicates. Cascade-deletes when trainer is removed; restricts delete of an assigned specialization.';

-- rooms
COMMENT ON TABLE  gym.rooms IS 'Physical spaces where classes and personal training take place.';
COMMENT ON COLUMN gym.rooms.capacity IS 'Minimum 2. NULL means no defined capacity limit.';

-- class_templates
COMMENT ON TABLE  gym.class_templates IS 'Catalogue of class types. No scheduling data lives here — only the definition of what a class is.';
COMMENT ON COLUMN gym.class_templates.capacity IS 'Overrides room capacity when set. NULL defers to the room capacity.';

-- class_recurrence_rules
COMMENT ON TABLE  gym.class_recurrence_rules IS 'Master repeating assignment: trainer + class + room + pattern. Day details live in rule_week_days (weekly) or rule_month_days (monthly). Daily rules need no day table.';
COMMENT ON COLUMN gym.class_recurrence_rules.frequency IS 'Determines which day-detail table applies: weekly → rule_week_days, monthly → rule_month_days, daily → neither.';

-- rule_week_days
COMMENT ON TABLE  gym.rule_week_days IS 'Days of the week for weekly recurrence rules. One row per day. Cascade-deletes when the parent rule is removed.';

-- rule_month_days
COMMENT ON TABLE  gym.rule_month_days IS 'Days of the month for monthly recurrence rules. One row per day. Days 29-31 may not exist in every month — the application must skip non-existent dates when materializing sessions.';

-- class_schedule
COMMENT ON TABLE  gym.class_schedule IS 'Materialized individual sessions generated from recurrence rules by a background job. class_id, trainer_id, and room_id are denormalized from the rule to support per-session overrides without modifying the master rule.';
COMMENT ON COLUMN gym.class_schedule.start_datetime IS 'Stored in UTC (TIMESTAMPTZ). Local time conversion is handled at the application layer.';
COMMENT ON COLUMN gym.class_schedule.end_datetime IS 'Must be strictly greater than start_datetime. Stored in UTC.';

-- memberships
COMMENT ON TABLE  gym.memberships IS 'Versioned membership products. Never edit a row — insert a new one when the price changes and set valid_to on the old row. Query WHERE valid_to IS NULL for currently active products.';
COMMENT ON COLUMN gym.memberships.currency IS 'ISO 4217 three-letter code. CHAR(3) enforces exact length. Defaults to UAH.';
COMMENT ON COLUMN gym.memberships.valid_to IS 'NULL means this product version is currently active.';

-- members
COMMENT ON TABLE gym.members IS 'A person registered as a gym member. Membership history is in members_memberships. UNIQUE on person_id enforces 1-to-1 with persons.';

-- members_memberships
COMMENT ON TABLE  gym.members_memberships IS 'Enrollment history: which versioned membership product a member signed up for and when. Multiple rows per member support renewals, upgrades, and lapses.';
COMMENT ON COLUMN gym.members_memberships.membership_id IS 'Points to the exact versioned product row, implicitly snapshotting the price at signup.';
COMMENT ON COLUMN gym.members_memberships.discount IS 'Percentage discount (0–100). Integer only — fractional discounts are not supported.';
COMMENT ON COLUMN gym.members_memberships.end_date IS 'NULL means the enrollment is open-ended.';

-- attendance
COMMENT ON TABLE  gym.attendance IS 'One row per member per class session. Tracks booking and physical check-in.';
COMMENT ON COLUMN gym.attendance.check_in_time IS 'NULL until the member physically arrives. Remains NULL for no_show and cancelled records.';

-- equipment
COMMENT ON TABLE  gym.equipment IS 'Gym equipment inventory. Not linked to scheduling — used for maintenance tracking only.';
COMMENT ON COLUMN gym.equipment.last_maintenance IS 'NULL means maintenance has never been recorded. Cannot be a future date.';

-- goals
COMMENT ON TABLE  gym.goals IS 'Fitness goals created by members. target_value is free-text to support numeric, distance, and habit-based goals.';
COMMENT ON COLUMN gym.goals.target_value IS 'Free-text target. Examples: ''75'', ''5km'', ''20 pull-ups''. No unit enforcement.';

-- progress
COMMENT ON TABLE  gym.progress IS 'Timestamped check-in entries against a goal. One entry per goal per day (uq_progress_goal_date). To update today''s entry, use UPDATE — a second INSERT on the same day will raise a unique violation. Cascade-deletes with the parent goal.';

-- personal_training
COMMENT ON TABLE  gym.personal_training IS 'One-on-one sessions outside the group class system. uq_member_time and uq_trainer_time prevent double-booking, but cross-checking against class_schedule is the application''s responsibility.';

-- trainer_work_schedule
COMMENT ON TABLE  gym.trainer_work_schedule IS 'Regular weekly availability for each trainer. One row per trainer per weekday (uq_trainer_day). Set is_active = FALSE to suspend a day without losing history.';

-- trainer_leaves
COMMENT ON TABLE  gym.trainer_leaves IS 'Leave requests for trainers. Approved leaves should be checked by the scheduling layer before generating class_schedule rows. Open-ended leaves (end_date IS NULL) must be closed via UPDATE.';
COMMENT ON COLUMN gym.trainer_leaves.end_date IS 'NULL means the leave has no defined end date (e.g. extended sick leave). Must be closed explicitly.';
